DROP DATABASE IF EXISTS mimo;
CREATE DATABASE mimo;


-- =====================================================================
-- 1. TABLAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- PERSONA
-- ---------------------------------------------------------------------
CREATE TABLE PERSONA (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido1 VARCHAR(100) NOT NULL,
    apellido2 VARCHAR(100),
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(254) NOT NULL,
    fecha_nacimiento DATE CHECK (fecha_nacimiento <= CURRENT_DATE) NOT NULL,
    calle VARCHAR(150) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    codigo_postal VARCHAR(10) NOT NULL,
    poblacion VARCHAR(100) NOT NULL,
    provincia VARCHAR(100) NOT NULL,
    telefono1 VARCHAR(20) NOT NULL,
    telefono2 VARCHAR(20),
    fecha_alta_cuenta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (id_persona),
    CONSTRAINT uq_persona_dni UNIQUE (dni),
    CONSTRAINT uq_persona_email UNIQUE (email)
);

-- ---------------------------------------------------------------------
-- CUESTIONARIO
-- ---------------------------------------------------------------------
CREATE TABLE CUESTIONARIO (
    id_cuestionario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_vivienda VARCHAR(20) CHECK (tipo_vivienda IN ('PISO', 'CHALET', 'CHALET_JARDIN', 'PARCELA')) NOT NULL,
    horas_solo INTEGER CHECK (horas_solo BETWEEN 0 AND 24) NOT NULL,
    tiene_otros_animales BOOLEAN NOT NULL,
    acepta_animal_enfermedad BOOLEAN NOT NULL,
    cerca_zonas_verdes BOOLEAN NOT NULL,
    CONSTRAINT pk_cuestionario PRIMARY KEY (id_cuestionario)	
);

-- ---------------------------------------------------------------------
-- SOLICITANTE
-- ---------------------------------------------------------------------
CREATE TABLE SOLICITANTE (
    id_persona BIGINT NOT NULL,
    id_referencia_salesforce VARCHAR(18),
    id_cuestionario BIGINT NOT NULL,
    CONSTRAINT pk_solicitante PRIMARY KEY (id_persona),
    CONSTRAINT uq_solicitante_salesforce UNIQUE (id_referencia_salesforce),
    CONSTRAINT uq_solicitante_cuestionario UNIQUE (id_cuestionario),
    CONSTRAINT fk_solicitante_persona
        FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona)
        	ON DELETE CASCADE,
    CONSTRAINT fk_solicitante_cuestionario
        FOREIGN KEY (id_cuestionario) REFERENCES CUESTIONARIO (id_cuestionario)
);

-- ---------------------------------------------------------------------
-- CENTRO_ADOPCION
-- ---------------------------------------------------------------------
CREATE TABLE CENTRO_ADOPCION (
    id_centro_adopcion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    calle VARCHAR(150) NOT NULL,
    numero  VARCHAR(10) NOT NULL,
    codigo_postal VARCHAR(10) NOT NULL,
    poblacion VARCHAR(100) NOT NULL,
    provincia VARCHAR(100) NOT NULL,
    email_contacto VARCHAR(254) NOT NULL,
    telefono1 VARCHAR(20) NOT NULL,
    telefono2 VARCHAR(20),
    id_referencia_salesforce VARCHAR(18),
    CONSTRAINT pk_centro_adopcion PRIMARY KEY (id_centro_adopcion),
    CONSTRAINT uq_centro_email UNIQUE (email_contacto),
    CONSTRAINT uq_centro_salesforce UNIQUE (id_referencia_salesforce)
);

-- ---------------------------------------------------------------------
-- ANIMAL
-- ---------------------------------------------------------------------
CREATE TABLE ANIMAL (
    id_animal BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE CHECK (fecha_nacimiento <= CURRENT_DATE) NOT NULL,
    sexo VARCHAR(10) CHECK (sexo IN ('MACHO', 'HEMBRA')) NOT NULL,
    esterilizado BOOLEAN NOT NULL,
    descripcion TEXT NOT NULL,
    sociabilidad VARCHAR(10) CHECK (sociabilidad IN ('ALTO', 'MEDIO', 'BAJO')) NOT NULL,
    nivel_energia VARCHAR(10) CHECK (nivel_energia IN ('ALTO', 'MEDIO', 'BAJO')) NOT NULL,
    tiene_enfermedad BOOLEAN NOT NULL DEFAULT FALSE,
    enfermedad VARCHAR(500) CHECK (tiene_enfermedad OR enfermedad IS NULL),
    estado VARCHAR(20) CHECK (estado IN ('DISPONIBLE', 'ACOGIDO', 'ADOPTADO')) NOT NULL DEFAULT 'DISPONIBLE',
    fecha_ingreso DATE NOT NULL,
    es_urgente BOOLEAN NOT NULL DEFAULT FALSE,
    id_referencia_salesforce VARCHAR(18),
    fecha_sincronizacion TIMESTAMP,
    id_centro_adopcion BIGINT NOT NULL,
    foto_url VARCHAR(500) NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id_animal),
    CONSTRAINT uq_animal_salesforce UNIQUE (id_referencia_salesforce),
    CONSTRAINT fk_animal_centro
        FOREIGN KEY (id_centro_adopcion) REFERENCES CENTRO_ADOPCION (id_centro_adopcion)
        	ON DELETE RESTRICT     
);

-- ---------------------------------------------------------------------
-- Subtipos de ANIMAL 
-- ---------------------------------------------------------------------
CREATE TABLE PERRO (
    id_animal BIGINT NOT NULL,
    raza VARCHAR(100) NOT NULL,
    tamano VARCHAR(10) CHECK (tamano IN ('MINI', 'PEQUENO', 'MEDIANO', 'GRANDE', 'GIGANTE')) NOT NULL,
    CONSTRAINT pk_perro PRIMARY KEY (id_animal),
    CONSTRAINT fk_perro_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal) 
        	ON DELETE CASCADE  
);

CREATE TABLE GATO (
    id_animal BIGINT NOT NULL,
    raza VARCHAR(100) NOT NULL,
    test_leucemia BOOLEAN,                -- NULL = sin test realizado
    CONSTRAINT pk_gato PRIMARY KEY (id_animal),
    CONSTRAINT fk_gato_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal) 
        	ON DELETE CASCADE
);

CREATE TABLE EXOTICO (
    id_animal BIGINT NOT NULL,
    tipo_especie VARCHAR(10) CHECK (tipo_especie IN ('CONEJO', 'AVE', 'REPTIL')) NOT NULL,
    necesidades_clima VARCHAR(255) NOT NULL,
    CONSTRAINT pk_exotico PRIMARY KEY (id_animal),
    CONSTRAINT fk_exotico_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal) 
        	ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- SOLICITUD
-- ---------------------------------------------------------------------
CREATE TABLE SOLICITUD (
    id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_persona BIGINT NOT NULL,
    id_animal BIGINT NOT NULL,
    tipo_tramite VARCHAR(10) CHECK (tipo_tramite IN ('ADOPCION', 'ACOGIDA')) NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    porcentaje_compatibilidad INTEGER CHECK (porcentaje_compatibilidad BETWEEN 0 AND 100) NOT NULL,
    motivos_compatibilidad TEXT NOT NULL,
    id_referencia_salesforce VARCHAR(18),
    estado_solicitud VARCHAR(10) CHECK (estado_solicitud IN ('PENDIENTE', 'ACEPTADO', 'DENEGADO')) NOT NULL DEFAULT 'PENDIENTE',
    fecha_sincronizacion TIMESTAMP,
    CONSTRAINT pk_solicitud PRIMARY KEY (id_solicitud),
    CONSTRAINT uq_solicitud_persona_animal_tramite
        UNIQUE (id_persona, id_animal, tipo_tramite),
    CONSTRAINT uq_solicitud_salesforce UNIQUE (id_referencia_salesforce),
    CONSTRAINT fk_solicitud_solicitante
        FOREIGN KEY (id_persona) REFERENCES SOLICITANTE (id_persona)
        	ON DELETE CASCADE,
    CONSTRAINT fk_solicitud_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal)
        	ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------
-- TRANSACCION_PAGO
-- ---------------------------------------------------------------------
CREATE TABLE TRANSACCION_PAGO (
    id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token_confirmacion VARCHAR(100),
    importe NUMERIC(10,2) CHECK (importe > 0) NOT NULL,
    fecha_cobro TIMESTAMP,
    estado VARCHAR(15) CHECK (estado IN ('COMPLETADO', 'PENDIENTE', 'FALLIDO')) NOT NULL DEFAULT 'PENDIENTE',
    id_persona BIGINT NOT NULL,
    id_animal BIGINT NOT NULL,
    CONSTRAINT pk_transaccion_pago PRIMARY KEY (id_transaccion),
    CONSTRAINT uq_transaccion_token UNIQUE (token_confirmacion),
    CONSTRAINT fk_transaccion_persona
        FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona)
        	ON DELETE RESTRICT,
    CONSTRAINT fk_transaccion_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal)
        	ON DELETE RESTRICT,
    CONSTRAINT ck_transaccion_completada
        CHECK (estado <> 'COMPLETADO'
               OR (token_confirmacion IS NOT NULL AND fecha_cobro IS NOT NULL))
);

-- ---------------------------------------------------------------------
-- FAVORITO
-- ---------------------------------------------------------------------
CREATE TABLE FAVORITO (
    id_favorito BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_persona BIGINT NOT NULL,
    id_animal BIGINT NOT NULL,
    fecha_marcado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_favorito PRIMARY KEY (id_favorito),
    CONSTRAINT uq_favorito_persona_animal UNIQUE (id_persona, id_animal),
    CONSTRAINT fk_favorito_persona
        FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona) 
        	ON DELETE CASCADE,
    CONSTRAINT fk_favorito_animal
        FOREIGN KEY (id_animal) REFERENCES ANIMAL (id_animal) 
        	ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- NOTIFICACION
-- ---------------------------------------------------------------------
CREATE TABLE NOTIFICACION (
    id_notificacion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(30) NOT NULL,
    mensaje TEXT NOT NULL,
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_persona BIGINT NOT NULL,
    id_solicitud BIGINT,
    CONSTRAINT pk_notificacion PRIMARY KEY (id_notificacion),
    CONSTRAINT fk_notificacion_persona
        FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona) 
        	ON DELETE CASCADE,
    CONSTRAINT fk_notificacion_solicitud
        FOREIGN KEY (id_solicitud) REFERENCES SOLICITUD (id_solicitud) 
        	ON DELETE CASCADE,
    CONSTRAINT ck_notificacion_tipo CHECK (tipo IN (
        'SOLICITUD_PENDIENTE', 'SOLICITUD_ACEPTADA', 'SOLICITUD_DENEGADA',
        'FAVORITO_NO_DISPONIBLE', 'DONACION_COMPLETADA', 'DONACION_FALLIDA')),
    CONSTRAINT ck_notificacion_solicitud
        CHECK (tipo NOT LIKE 'SOLICITUD%' OR id_solicitud IS NOT NULL)
);




-- =====================================================================
-- 2. TRIGGERS
-- =====================================================================

-- ---------------------------------------------------------------------
-- Cuestionario: la fecha de actualización se pone sola al editarlo.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_cuestionario_fecha_actualizacion()
RETURNS trigger AS $$
BEGIN
    NEW.fecha_actualizacion := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cuestionario_fecha_actualizacion
BEFORE UPDATE
ON CUESTIONARIO
FOR EACH ROW
EXECUTE FUNCTION fn_cuestionario_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- Cuestionario: Al borrar un solicitante se borra también su cuestionario
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_solicitante_borra_cuestionario()
RETURNS trigger AS $$
BEGIN
    DELETE FROM cuestionario
	WHERE id_cuestionario = OLD.id_cuestionario;
    
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_solicitante_borra_cuestionario
AFTER DELETE 
ON SOLICITANTE
FOR EACH ROW 
EXECUTE FUNCTION fn_solicitante_borra_cuestionario();

-- ---------------------------------------------------------------------
-- Animal: Un animal no puede estar a la vez en dos subtipos
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_animal_subtipo_unico()
RETURNS trigger AS $$
BEGIN
    IF (TG_TABLE_NAME <> 'perro'   AND EXISTS (SELECT 1 FROM perro   WHERE id_animal = NEW.id_animal))
    OR (TG_TABLE_NAME <> 'gato'    AND EXISTS (SELECT 1 FROM gato    WHERE id_animal = NEW.id_animal))
    OR (TG_TABLE_NAME <> 'exotico' AND EXISTS (SELECT 1 FROM exotico WHERE id_animal = NEW.id_animal))
    THEN
        RAISE EXCEPTION 'El animal % ya pertenece a otro subtipo', NEW.id_animal;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_perro_subtipo_unico
BEFORE INSERT 
ON PERRO
FOR EACH ROW 
EXECUTE FUNCTION fn_animal_subtipo_unico();

CREATE TRIGGER trg_gato_subtipo_unico
BEFORE INSERT 
ON GATO
FOR EACH ROW 
EXECUTE FUNCTION fn_animal_subtipo_unico();

CREATE TRIGGER trg_exotico_subtipo_unico
BEFORE INSERT 
ON EXOTICO
FOR EACH ROW 
EXECUTE FUNCTION fn_animal_subtipo_unico();

-- ---------------------------------------------------------------------
-- Animal: Todo animal tiene que tener fila en uno de los subtipos. 
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_animal_tiene_subtipo()
RETURNS trigger AS $$
BEGIN
    IF NOT (EXISTS (SELECT 1 FROM perro   WHERE id_animal = NEW.id_animal)
         OR EXISTS (SELECT 1 FROM gato    WHERE id_animal = NEW.id_animal)
         OR EXISTS (SELECT 1 FROM exotico WHERE id_animal = NEW.id_animal))
    THEN
        RAISE EXCEPTION 'El animal % debe ser perro, gato o exotico', NEW.id_animal;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_animal_tiene_subtipo
AFTER INSERT 
ON ANIMAL
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW 
EXECUTE FUNCTION fn_animal_tiene_subtipo();



